### ISSUE TITLE
Cannot find module 'eslint-config-you-dont-need-lodash-underscore:compatible-error'

### ISSUE THREAD

**Issue by keithkml** [you-dont-need/You-Dont-Need-Lodash-Underscore#88]
I'm not sure what I'm doing wrong. I installed `eslint-plugin-you-dont-need-lodash-underscore` via NPM but ESLint can't find any of the configs. 

Note that ESLint *can* find the plugin - when I enable a rule like `"you-dont-need-lodash-underscore/for-each": "error",` eslint runs successfully.

```
% node_modules/.bin/eslint src
Cannot find module 'eslint-config-you-dont-need-lodash-underscore:compatible-error'
Referenced from: /Users/keithlea/Code/thrift2flow/.eslintrc
Error: Cannot find module 'eslint-config-you-dont-need-lodash-underscore:compatible-error'
Referenced from: /Users/keithlea/Code/thrift2flow/.eslintrc
    at ModuleResolver.resolve (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config/config-file.js:532:26)
    at configExtends.reduceRight.e (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/keithlea/Code/thrift2flow/node_modules/eslint/lib/config.js:260:26)
[keithlea:~/Code/thrift2flow] master(+3/-2,+1/-1)* 2d23h56m11s 1 ± npm ls eslint
thrift2flow@0.1.0 /Users/keithlea/Code/thrift2flow
└── eslint@3.19.0

% npm ls eslint-plugin-you-dont-need-lodash-underscore
thrift2flow@0.1.0 /Users/keithlea/Code/thrift2flow
└── eslint-plugin-you-dont-need-lodash-underscore@6.2.1

% npm -v
4.0.5

% node -v
v6.10.0
```

**Comment by keithkml** [comment]
After some Googling I found this syntax:
```
  "extends": ["eslint-config-uber-es2015", "plugin:you-dont-need-lodash-underscore/compatible"],
```
That seems to "work" but now I get a bunch of weird errors:

```
src/main/convert.js
  3:1  error    Definition for rule 'trim' was not found           trim
  3:1  error    Definition for rule 'concat' was not found         concat
  3:1  error    Definition for rule 'join' was not found           join
  3:1  error    Definition for rule 'last-index-of' was not found  last-index-of
  3:1  error    Definition for rule 'reverse' was not found        reverse
  3:1  error    Definition for rule 'fill' was not found           fill
  3:1  error    Definition for rule 'find' was not found           find
  3:1  error    Definition for rule 'detect' was not found         detect
  3:1  error    Definition for rule 'find-index' was not found     find-index
  3:1  error    Definition for rule 'is-nan' was not found         is-nan
  3:1  error    Definition for rule 'keys' was not found           keys
  3:1  error    Definition for rule 'extend-own' was not found     extend-own
  3:1  error    Definition for rule 'assign' was not found         assign
  3:1  error    Definition for rule 'values' was not found         values
  3:1  error    Definition for rule 'entries' was not found        entries
  3:1  error    Definition for rule 'to-pairs' was not found       to-pairs
  3:1  error    Definition for rule 'pairs' was not found          pairs
  3:1  error    Definition for rule 'to-lower' was not found       to-lower
  3:1  error    Definition for rule 'to-upper' was not found       to-upper
  3:1  error    Definition for rule 'index-of' was not found       index-of
  3:1  error    Definition for rule 'repeat' was not found         repeat
  3:1  warning  Definition for rule 'each' was not found           each
  3:1  warning  Definition for rule 'for-each' was not found       for-each
  3:1  warning  Definition for rule 'every' was not found          every
  3:1  warning  Definition for rule 'all' was not found            all
  3:1  warning  Definition for rule 'filter' was not found         filter
  3:1  warning  Definition for rule 'select' was not found         select
  3:1  warning  Definition for rule 'map' was not found            map
  3:1  warning  Definition for rule 'collect' was not found        collect
  3:1  warning  Definition for rule 'reduce' was not found         reduce
  3:1  warning  Definition for rule 'inject' was not found         inject
  3:1  warning  Definition for rule 'foldl' was not found          foldl
  3:1  warning  Definition for rule 'reduce-right' was not found   reduce-right
  3:1  warning  Definition for rule 'foldr' was not found          foldr
  3:1  warning  Definition for rule 'size' was not found           size
  3:1  warning  Definition for rule 'some' was not found           some
  3:1  warning  Definition for rule 'any' was not found            any
  3:1  warning  Definition for rule 'includes' was not found       includes
  3:1  warning  Definition for rule 'contains' was not found       contains

src/main/index.js
  4:1  error    Definition for rule 'trim' was not found           trim
  4:1  error    Definition for rule 'concat' was not found         concat
  4:1  error    Definition for rule 'join' was not found           join
  4:1  error    Definition for rule 'last-index-of' was not found  last-index-of
  4:1  error    Definition for rule 'reverse' was not found        reverse
  4:1  error    Definition for rule 'fill' was not found           fill
  4:1  error    Definition for rule 'find' was not found           find
...
```
etc etc - same errors for every file.

**Comment by stevemao** [comment]
Sorry about that. Could you try https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/pull/89?

**Comment by keithkml** [comment]
Sure, how do I do that? Can I point NPM to a pull request or something?

**Comment by stevemao** [comment]
@keithkml I use usually `npm link`.

**Comment by keithkml** [comment]
Looks great!

**Comment by stevemao** [comment]
Thanks for trying it out @keithkml 😄
